### ISSUE TITLE
Relies on deprecated AnimationTiming.playbackRate

### ISSUE THREAD

**Issue by tjsavage** [Polymer/core-animation#19]
As per the [WebAnimation spec/polyfill release notes](https://github.com/web-animations/web-animations-js/blob/170b3f71000b5a4b22a65c3d76dc662ee4b78fae/History.md), the `AnimationTiming.playbackRate` call is being deprecated. Currently `core-animation`'s use of `web-animation` throws a console warning of this deprecation.

Exercised at least in `paper-dropdown` - see http://jsbin.com/zuqoqidixo/1/edit?html,console,output

**Comment by JitendraZaa** [comment]
What is the solution to this message ? I am not able to find anything.

**Comment by sharmamo** [comment]
+1 I am seeing this issue as well. Is there an update to this?

**Comment by tjsavage** [comment]
This is fixed now - core-animation was updated to rely on [web-animation 1.0.6](https://github.com/web-animations/web-animations-js/releases/tag/1.0.6) which suppresses this warning.
