### ISSUE TITLE
Child animations don't throw finish events

### ISSUE THREAD

**Issue by clyfe** [Polymer/core-animation#20]
Let's say I have an animation built out of smaller animations:

```html
<core-animation-group type="par" on-core-animation-finish="{{done}}">
  <core-animation-group type="seq" on-core-animation-finish="{{partial}}">
    ... animations
  <core-animation-group>
  ... animations
<core-animation-group>
```

The `done` callback gets executed, but the `partial` callback for the intermediary (inner) animation doesn't. Is it by design ?

**Comment by morethanreal** [comment]
Yes, the current web animations spec defines the `finish` event on the animation player, so there is only one event in your example. There is possibility to define more events in future versions of the spec however.
